export const experiences = [
  {
    title: "Custom Applications Development Engineer",
    companyName: "KPMG",
    workLocation: "Bangalore",
    desc: null,
    start: "July 2026",
    startISO: "2026-07",
    end: null,
    endISO: null,
  },
  {
    title: "Associate Software Development Engineer",
    companyName: "NTT Data",
    workLocation: "Remote",
    desc: "Modernizing Nebula, a cloud billing and provisioning platform for NTT affiliates.",
    start: "June 2024",
    startISO: "2024-06",
    end: "June 2026",
    endISO: "2026-06",
  },
  {
    title: "Software Developer Intern",
    companyName: "Seovigil (powered by Botpresso)",
    workLocation: "Remote",
    desc: "Developed an admin platform to optimize data collection for analytics and decisions.",
    start: "January 2024",
    startISO: "2024-01",
    end: "June 2024",
    endISO: "2024-06",
  },
  {
    title: "Web Application Developer",
    companyName: "Ginger Partners",
    workLocation: "Remote",
    desc: "Developed API endpoints and an ATS, boosting efficiency by 80%.",
    start: "October 2023",
    startISO: "2023-10",
    end: "January 2024",
    endISO: "2024-01",
  },
  {
    title: "Full Stack Developer",
    companyName: "MRIIRS",
    workLocation: "Faridabad, Haryana",
    desc: "Created a portal for teachers to track submitted research papers.",
    start: "September 2022",
    startISO: "2022-09",
    end: "February 2023",
    endISO: "2023-02",
  },
];
