export const sideProjects = [
  {
    title: 'EZNotify',
    projLink: 'https://www.eznotify.dev/',
    desc: "a developer friendly SDK for sending multi-channel notifications like email, SMS, WhatsApp, push and more built for reliability at scale.",
    descLink: "/projects/eznotify/",
    userCount: null,
    activelyWorking: true,
  },
  {
    title: 'DecodeMyCode',
    projLink: 'https://www.decodemycode.com/',
    desc: "an AI powered SaaS that turns any code into clear explanations, flowcharts and summaries.",
    descLink: "/projects/decode-mycode/",
    userCount: '5 users',
    activelyWorking: false,
  },
  {
    title: 'CollabWrite',
    projLink: 'https://collabwrite.appwrite.network/',
    desc: "an open source, real-time collaborative knowledge-sharing platform.",
    descLink: "/projects/collab-write/",
    userCount: '10 users',
    activelyWorking: false,
  },
  {
    title: 'NagarIQ',
    projLink: 'https://nagar-iq.shivamtaneja.com/',
    desc: "an AI-powered system that understands the world around it.",
    descLink: "/projects/nagar-iq/",
    userCount: '12 users',
    activelyWorking: false,
  },
  {
    title: 'Tilt Bot',
    projLink: 'https://tilt-bot.shivamtaneja.com/',
    desc: "an AI-powered gaming roast generator for witty, non-toxic comebacks.",
    descLink: "/projects/tilt-bot/",
    userCount: '05 users',
    activelyWorking: false,
  },
  {
    title: 'Chat Mingle',
    projLink: 'https://chat-mingle.shivamtaneja.com/',
    desc: "a fun, experimental chat app.",
    descLink: "/projects/chat-mingle/",
    userCount: '19 users',
    activelyWorking: false,
  },
  {
    title: 'Circle Catcher',
    projLink: 'https://circle-game.shivamtaneja.com/',
    desc: "a game where you grow by eating smaller circles while avoiding larger ones.",
    descLink: "/projects/circle-catcher/",
    userCount: '09 users',
    activelyWorking: false,
  },
  {
    title: 'Career Guide Hub (Freelance)',
    projLink: 'https://www.saina.co.in/',
    desc: "a web app with assessments to provide personalized career recommendations, empowering student decisions.",
    descLink: "/projects/career-guidance/",
    userCount: null,
    activelyWorking: false,
  },
];
