export const sideProjects = [
  {
    title: 'CollabWrite',
    projLink: 'https://collabwrite.appwrite.network/',
    desc: "an open source, real-time collaborative knowledge-sharing platform.",
    descLink: "/project/collab-write/",
    userCount: '10 users',
    activelyWorking: true,
  },
  {
    title: 'NagarIQ',
    projLink: 'https://nagar-iq.shivamtaneja.com/',
    desc: "an AI-powered system that understands the world around it.",
    descLink: "/project/nagar-iq/",
    userCount: null,
    activelyWorking: true,
  },
  {
    title: 'Tilt Bot',
    projLink: 'https://tilt-bot.shivamtaneja.com/',
    desc: "an AI-powered gaming roast generator for witty, non-toxic comebacks.",
    descLink: "/project/tilt-bot/",
    userCount: '05 users',
    activelyWorking: false,
  },
  {
    title: 'Chat Mingle',
    projLink: 'https://chat-mingle.shivamtaneja.com/',
    desc: "a fun, experimental chat app.",
    descLink: "/project/chat-mingle/",
    userCount: '19 users',
    activelyWorking: false,
  },
  {
    title: 'Circle Catcher',
    projLink: 'https://circle-game.shivamtaneja.com/',
    desc: "a game where you grow by eating smaller circles while avoiding larger ones.",
    descLink: "/project/circle-catcher/",
    userCount: '09 users',
    activelyWorking: false,
  },
  {
    title: 'Career Guide Hub (Freelance)',
    projLink: 'https://www.saina.co.in/',
    desc: "a web app with assessments to provide personalized career recommendations, empowering student decisions.",
    descLink: "/project/career-guidance/",
    userCount: null,
    activelyWorking: false,
  },
];
